version: 2
jobs:
  build:
    docker:
      - image: developernaren/reactphp-gd
    steps:
      - checkout

      - run: apt update

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - run: ./vendor/bin/phpunit
